- name: required packages are installed
  become: true
  package:
    name:
      - make
      - git

- name: pull tic docker
  become: true
  git:
    repo: https://github.com/martinais/docker-martinais.git
    dest: /srv/docker-martinais/
    force: yes
  register: code
 
- name: environment files are downloaded for remote project
  become: true
  fetch:
    src: "{{ item.remote }}"
    dest: "{{ item.local }}"
    flat: true
  loop:
    - { remote: '/srv/docker-martinais/.env.j2', local: '/tmp/.env.j2' }
    - { remote: '/srv/docker-martinais/frontend/.env.production.j2', local: '/tmp/.env.production.j2' }

- name: environment files for main docker are generated
  become: true
  template:
    src: "{{ item.local }}"
    dest: "{{ item.remote }}"
  loop:
    - { remote: '/srv/docker-martinais/.env', local: '/tmp/.env.j2' }
    - { remote: '/srv/docker-martinais/frontend/.env.production', local: '/tmp/.env.production.j2' }

- name: app is deployed
  become: true
  docker_compose:
    project_name: martinade
    project_src: /srv/docker-martinais/
    build: true
    nocache: true
    recreate: always
  when: code.changed

- name: initiate project
  become: true
  make:
    chdir: /srv/docker-martinais
    target: reset
  when: code.changed
